#pragma once
#define WINDOW_WIDTH 1024
#define WINDOW_HEIGHT 600

#define ENTITY_AMOUNT 6
#define FONT_SIZE 24
#define INITIAL_UPWARD_VELOCITY (-360)
#define GRAVITY 150
#define WINDOW_BORDER_PADDING 16